### ISSUE TITLE
ci has been failing for past month

### ISSUE THREAD

**Issue by somebody1234** [GUI/lua-docker#3]
ever since https://github.com/GUI/lua-docker/actions/runs/399872793
docker hub also says latest update is 1 month ago, so it's missing things like the alpine3.11 and 3.12 images

**Comment by GUI** [comment]
Thanks for the heads up! There were a couple causes of these failures, but things should be fixed now (mainly by https://github.com/GUI/lua-docker/commit/56c7e2e00ae0b98303a789088437f59d04c2654a and https://github.com/GUI/lua-docker/commit/403f9aa9c0afaf042463fb0c70466bca1433016f)
